function asyncGeneratorStep(z,x,N,M,H,F,D){try{var I=z[F](D),E=I.value}catch(O){N(O);return}I.done?x(E):Promise.resolve(E).then(M,H)}function _asyncToGenerator(z){return function(){var x=this,N=arguments;return new Promise(function(M,H){function F(E){asyncGeneratorStep(I,M,H,F,D,"next",E)}function D(E){asyncGeneratorStep(I,M,H,F,D,"throw",E)}var I=z.apply(x,N);F(void 0)})}}
function _typeof(z){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(x){return typeof x}:function(x){return x&&"function"===typeof Symbol&&x.constructor===Symbol&&x!==Symbol.prototype?"symbol":typeof x};return _typeof(z)}var _regenerator;
(function(){var z=function(x){function N(a,b,d,m){b=Object.create((b&&b.prototype instanceof H?b:H).prototype);m=new P(m||[]);b._invoke=O(a,d,m);return b}function M(a,b,d){try{return{type:"normal",arg:a.call(b,d)}}catch(m){return{type:"throw",arg:m}}}function H(){}function F(){}function D(){}function I(a){["next","throw","return"].forEach(function(b){a[b]=function(d){return this._invoke(b,d)}})}function E(a,b){function d(e,t,w,A){e=M(a[e],a,t);if("throw"===e.type)A(e.arg);else{var u=e.arg;return(e=
u.value)&&"object"===_typeof(e)&&C.call(e,"__await")?b.resolve(e.__await).then(function(y){d("next",y,w,A)},function(y){d("throw",y,w,A)}):b.resolve(e).then(function(y){u.value=y;w(u)},function(y){return d("throw",y,w,A)})}}var m;this._invoke=function(e,t){function w(){return new b(function(A,u){d(e,t,A,u)})}return m=m?m.then(w,w):w()}}function O(a,b,d){var m=n;return function(e,t){if(m===q)throw Error("Generator is already running");if(m===c){if("throw"===e)throw t;return S()}d.method=e;for(d.arg=
t;;){if(e=d.delegate)if(e=T(e,d)){if(e===h)continue;return e}if("next"===d.method)d.sent=d._sent=d.arg;else if("throw"===d.method){if(m===n)throw m=c,d.arg;d.dispatchException(d.arg)}else"return"===d.method&&d.abrupt("return",d.arg);m=q;e=M(a,b,d);if("normal"===e.type){m=d.done?c:k;if(e.arg===h)continue;return{value:e.arg,done:d.done}}"throw"===e.type&&(m=c,d.method="throw",d.arg=e.arg)}}}function T(a,b){var d=a.iterator[b.method];if(d===G){b.delegate=null;if("throw"===b.method){if(a.iterator["return"]&&
(b.method="return",b.arg=G,T(a,b),"throw"===b.method))return h;b.method="throw";b.arg=new TypeError("The iterator does not provide a 'throw' method")}return h}d=M(d,a.iterator,b.arg);if("throw"===d.type)return b.method="throw",b.arg=d.arg,b.delegate=null,h;d=d.arg;if(!d)return b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,h;if(d.done)b[a.resultName]=d.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=G);else return d;b.delegate=null;return h}
function U(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function Q(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function P(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(U,this);this.reset(!0)}function R(a){if(a){var b=a[p];if(b)return b.call(a);if("function"===typeof a.next)return a;if(!isNaN(a.length)){var d=-1;b=function e(){for(;++d<a.length;)if(C.call(a,d))return e.value=a[d],e.done=!1,e;e.value=
G;e.done=!0;return e};return b.next=b}}return{next:S}}function S(){return{value:G,done:!0}}var V=Object.prototype,C=V.hasOwnProperty,G,v="function"===typeof Symbol?Symbol:{},p=v.iterator||"@@iterator",r=v.asyncIterator||"@@asyncIterator",l=v.toStringTag||"@@toStringTag";x.wrap=N;var n="suspendedStart",k="suspendedYield",q="executing",c="completed",h={};v={};v[p]=function(){return this};var g=Object.getPrototypeOf;(g=g&&g(g(R([]))))&&g!==V&&C.call(g,p)&&(v=g);var f=D.prototype=H.prototype=Object.create(v);
F.prototype=f.constructor=D;D.constructor=F;D[l]=F.displayName="GeneratorFunction";x.isGeneratorFunction=function(a){return(a="function"===typeof a&&a.constructor)?a===F||"GeneratorFunction"===(a.displayName||a.name):!1};x.mark=function(a){Object.setPrototypeOf?Object.setPrototypeOf(a,D):(a.__proto__=D,l in a||(a[l]="GeneratorFunction"));a.prototype=Object.create(f);return a};x.awrap=function(a){return{__await:a}};I(E.prototype);E.prototype[r]=function(){return this};x.AsyncIterator=E;x.async=function(a,
b,d,m,e){void 0===e&&(e=Promise);var t=new E(N(a,b,d,m),e);return x.isGeneratorFunction(b)?t:t.next().then(function(w){return w.done?w.value:t.next()})};I(f);f[l]="Generator";f[p]=function(){return this};f.toString=function(){return"[object Generator]"};x.keys=function(a){var b=[],d;for(d in a)b.push(d);b.reverse();return function e(){for(;b.length;){var t=b.pop();if(t in a)return e.value=t,e.done=!1,e}e.done=!0;return e}};x.values=R;P.prototype={constructor:P,reset:function(a){this.next=this.prev=
0;this.sent=this._sent=G;this.done=!1;this.delegate=null;this.method="next";this.arg=G;this.tryEntries.forEach(Q);if(!a)for(var b in this)"t"===b.charAt(0)&&C.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=G)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(u,y){t.type="throw";t.arg=a;d.next=u;y&&(d.method="next",d.arg=G);return!!y}if(this.done)throw a;for(var d=this,m=this.tryEntries.length-1;0<=
m;--m){var e=this.tryEntries[m],t=e.completion;if("root"===e.tryLoc)return b("end");if(e.tryLoc<=this.prev){var w=C.call(e,"catchLoc"),A=C.call(e,"finallyLoc");if(w&&A){if(this.prev<e.catchLoc)return b(e.catchLoc,!0);if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else if(w){if(this.prev<e.catchLoc)return b(e.catchLoc,!0)}else if(A){if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(a,b){for(var d=this.tryEntries.length-
1;0<=d;--d){var m=this.tryEntries[d];if(m.tryLoc<=this.prev&&C.call(m,"finallyLoc")&&this.prev<m.finallyLoc){var e=m;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=b&&b<=e.finallyLoc&&(e=null);d=e?e.completion:{};d.type=a;d.arg=b;return e?(this.method="next",this.next=e.finallyLoc,h):this.complete(d)},complete:function(a,b){if("throw"===a.type)throw a.arg;"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===
a.type&&b&&(this.next=b);return h},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var d=this.tryEntries[b];if(d.finallyLoc===a)return this.complete(d.completion,d.afterLoc),Q(d),h}},"catch":function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var d=this.tryEntries[b];if(d.tryLoc===a){a=d.completion;if("throw"===a.type){var m=a.arg;Q(d)}return m}}throw Error("illegal catch attempt");},delegateYield:function(a,b,d){this.delegate={iterator:R(a),resultName:b,nextLoc:d};"next"===this.method&&
(this.arg=G);return h}};return x}("object"===("undefined"===typeof module?"undefined":_typeof(module))?module.exports:{});try{_regenerator=z}catch(x){Function("r","_regenerator = r")(z)}})();
(function(){function z(v){var p=null;v==seraph_accel.Gen.hr.E_CONTEXT_EXPIRED?p=C("OpSrvCtxExpired","admin.Manage","seraphinite-accelerator"):seraph_accel.Gen.hr.Fail(v)&&(p=G(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),v));return p}function x(){x=_asyncToGenerator(_regenerator.mark(function r(p){return _regenerator.wrap(function(l){for(;;)switch(l.prev=l.next){case 0:return jQuery(p).attr("disabled",!0),l.prev=1,l.next=4,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"LogClear",{}),type:"POST",data:"",dataType:"json",cache:!1});case 4:l.next=8;break;case 6:l.prev=6,l.t0=l["catch"](1);case 8:jQuery(p).attr("disabled",!1);case 9:case "end":return l.stop()}},r,this,[[1,6]])}));return x.apply(this,arguments)}function N(){N=_asyncToGenerator(_regenerator.mark(function l(p,r){var n,k,q,c,h,g;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:n=jQuery(p.parentNode).closest(".blck").first();k=n.find(".seraph_accel_spinner");n.find(".content");q=
n.find('input[type="button"]:not(.cancel)');c=n.find('input[type="button"].cancel');if(!r){f.next=23;break}q.prop("disabled",!0);k.show();seraph_accel.Manager._int.notRefreshStat=!0;h=null;f.prev=10;f.next=13;return jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"UpdateStatBegin",{}),cache:!1,dataType:"json"});case 13:g=f.sent;seraph_accel.Gen.hr.Fail(g)&&(h=G(C("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),g));f.next=20;break;case 17:f.prev=17,
f.t0=f["catch"](10),h="HTTP "+f.t0.status;case 20:return h&&(alert(h),q.prop("disabled",!1),k.hide()),delete seraph_accel.Manager._int.notRefreshStat,f.abrupt("return");case 23:return c.prop("disabled",!0),seraph_accel.Manager._int.notRefreshStat=!0,h=null,f.prev=26,f.next=29,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"UpdateStatCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 29:g=f.sent;h=z(g);f.next=37;break;case 33:f.prev=33,f.t1=f["catch"](26),
h="HTTP "+f.t1.status,c.prop("disabled",!1);case 37:h&&alert(h),delete seraph_accel.Manager._int.notRefreshStat;case 39:case "end":return f.stop()}},l,this,[[10,17],[26,33]])}));return N.apply(this,arguments)}function M(v){switch(v){case 0:return C("OpDescr_Invalidate","admin.Manage","seraphinite-accelerator");case 3:return C("OpDescr_CheckInvalidate","admin.Manage","seraphinite-accelerator");case 2:return C("OpDescr_Delete","admin.Manage","seraphinite-accelerator");case 10:return C("OpDescr_SrvDel",
"admin.Manage","seraphinite-accelerator")}return""+v}function H(){H=_asyncToGenerator(_regenerator.mark(function r(p){var l,n,k,q;return _regenerator.wrap(function(c){for(;;)switch(c.prev=c.next){case 0:return l=jQuery(p.parentNode).closest(".blck").first(),n=l.find('input[type="button"].cancel'),n.prop("disabled",!0),k=null,c.prev=4,c.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"PostUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:q=
c.sent;k=z(q);c.next=14;break;case 11:c.prev=11,c.t0=c["catch"](4),k="HTTP "+c.t0.status;case 14:k&&alert(k);case 15:case "end":return c.stop()}},r,this,[[4,11]])}));return H.apply(this,arguments)}function F(){F=_asyncToGenerator(_regenerator.mark(function r(p){var l,n,k,q;return _regenerator.wrap(function(c){for(;;)switch(c.prev=c.next){case 0:return l=jQuery(p.parentNode).closest(".blck").first(),n=l.find('input[type="button"].cancel'),n.prop("disabled",!0),k=null,c.prev=4,c.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"ScheUpdCancel",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:q=c.sent;k=z(q);c.next=14;break;case 11:c.prev=11,c.t0=c["catch"](4),k="HTTP "+c.t0.status;case 14:k&&alert(k);case 15:case "end":return c.stop()}},r,this,[[4,11]])}));return F.apply(this,arguments)}function D(){D=_asyncToGenerator(_regenerator.mark(function r(p){var l,n,k,q,c,h;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return l=jQuery(p.parentNode).closest(".blck").first(),n=l.find(".seraph_accel_spinner"),
k=l.find('input[type="button"]:not(.cancel)'),q=l.find('input[type="button"].cancel'),n.show(),k.prop("disabled",!0),q.prop("disabled",!1),seraph_accel.Manager._int.notRefreshExtDp=!0,c=null,g.prev=9,g.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdBegin",{}),type:"POST",data:"",cache:!1,dataType:"json"});case 12:h=g.sent;c=z(h);g.next=19;break;case 16:g.prev=16,g.t0=g["catch"](9),c="HTTP "+g.t0.status;case 19:c&&alert(c),delete seraph_accel.Manager._int.notRefreshExtDp;
case 21:case "end":return g.stop()}},r,this,[[9,16]])}));return D.apply(this,arguments)}function I(){I=_asyncToGenerator(_regenerator.mark(function r(p){var l,n,k,q;return _regenerator.wrap(function(c){for(;;)switch(c.prev=c.next){case 0:return l=jQuery(p.parentNode).closest(".blck").first(),n=l.find('input[type="button"].cancel'),n.prop("disabled",!0),k=null,c.prev=4,c.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ExtDbUpdCancel",{}),type:"POST",data:"",
cache:!1,dataType:"json"});case 7:q=c.sent;k=z(q);c.next=14;break;case 11:c.prev=11,c.t0=c["catch"](4),k="HTTP "+c.t0.status;case 14:k&&alert(k);case 15:case "end":return c.stop()}},r,this,[[4,11]])}));return I.apply(this,arguments)}function E(){E=_asyncToGenerator(_regenerator.mark(function n(p,r,l){var k,q,c,h,g,f,a,b,d,m,e,t,w,A;return _regenerator.wrap(function(u){for(;;)switch(u.prev=u.next){case 0:return k=jQuery(p.parentNode).closest(".blck").first(),q=k.find(".seraph_accel_spinner"),c=k.find(".descr"),
h=k.find('input[type="button"]:not(.cancel)'),g=k.find('input[type="button"].cancel'),f=k.find("#seraph_accel_views"),a=k.find("#seraph_accel_geos"),b=[],f.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(f.get()),b=seraph_accel.Ui.TokensList.GetVal(f.get())),d=[],a.get()&&(seraph_accel.Ui.TokensMetaTree.Apply(a.get()),d=seraph_accel.Ui.TokensList.GetVal(a.get()).filter(function(y){return"_"!==y})),e=String(k.find(".type").val()),"uri"===e?m=k.find(".uri").val():0===e.indexOf("uri:")&&(m=e.substr(4),
e="uri"),m=seraph_accel.Gen.StrReplaceAll(String(m),["\r","\n","*"],["",";","{ASTRSK}"]),q.show(),c.show(),c.text(M(r)),h.prop("disabled",!0),g.prop("disabled",!1),seraph_accel.Manager._int.notRefreshOp=!0,t={cache:!1,dataType:"json"},512>m.length?t.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",{type:e,op:r,uri:m,v:b.join(),g:d.length?d.join():void 0,_wpnonce:l}):(t.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",
{type:e,op:r,v:b.join(),g:d.length?d.join():void 0,_wpnonce:l}),t.type="POST",t.contentType="application/x-www-form-urlencoded",t.data="uri="+encodeURIComponent(m)),w=null,u.prev=23,u.next=26,jQuery.ajax(t);case 26:A=u.sent;w=z(A);u.next=33;break;case 30:u.prev=30,u.t0=u["catch"](23),w="HTTP "+u.t0.status;case 33:w&&alert(w),delete seraph_accel.Manager._int.notRefreshOp;case 35:case "end":return u.stop()}},n,this,[[23,30]])}));return E.apply(this,arguments)}function O(){O=_asyncToGenerator(_regenerator.mark(function n(p,
r,l){var k,q,c,h;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:return k=jQuery(p.parentNode).closest(".blck").first(),q=k.find('input[type="button"].cancel'),q.prop("disabled",!0),c=null,g.prev=4,g.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpCancel",{op:r,_wpnonce:l}),type:"POST",data:"",cache:!1,dataType:"json"});case 7:h=g.sent;c=z(h);g.next=14;break;case 11:g.prev=11,g.t0=g["catch"](4),c="HTTP "+g.t0.status;case 14:c&&
alert(c);case 15:case "end":return g.stop()}},n,this,[[4,11]])}));return O.apply(this,arguments)}function T(){T=_asyncToGenerator(_regenerator.mark(function n(p,r,l){var k,q,c,h,g;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:return k=jQuery(p.parentNode).closest(".blck").first(),q=k.find(".seraph_accel_spinner"),c=k.find('input[type="button"]'),q.show(),c.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,h=null,f.prev=7,f.next=10,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"QueueDelete",{allSites:r?!0:void 0,_wpnonce:l}),type:"GET",cache:!1,dataType:"json"});case 10:g=f.sent;h=z(g);f.next=17;break;case 14:f.prev=14,f.t0=f["catch"](7),h="HTTP "+f.t0.status;case 17:h&&(alert(h),q.hide(),c.prop("disabled",!1)),delete seraph_accel.Manager._int.notRefreshQueueDeleting;case 19:case "end":return f.stop()}},n,this,[[7,14]])}));return T.apply(this,arguments)}function U(){U=_asyncToGenerator(_regenerator.mark(function n(p,r,l){var k,q,c,h,g;return _regenerator.wrap(function(f){for(;;)switch(f.prev=
f.next){case 0:return k=jQuery(p.parentNode).closest(".blck").first(),q=k.find(".seraph_accel_spinner"),c=k.find('input[type="button"]'),q.show(),c.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,h=null,f.prev=7,f.next=10,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"QueuePause",{v:r,_wpnonce:l}),type:"POST",cache:!1,dataType:"json"});case 10:g=f.sent;h=z(g);f.next=17;break;case 14:f.prev=14,f.t0=f["catch"](7),h="HTTP "+f.t0.status;
case 17:h&&(alert(h),q.hide(),c.prop("disabled",!1)),delete seraph_accel.Manager._int.notRefreshQueueDeleting;case 19:case "end":return f.stop()}},n,this,[[7,14]])}));return U.apply(this,arguments)}function Q(){Q=_asyncToGenerator(_regenerator.mark(function n(p,r,l){var k,q,c,h,g;return _regenerator.wrap(function(f){for(;;)switch(f.prev=f.next){case 0:if(confirm(C("ItemCancelConfirm","admin.Manage_Queue","seraphinite-accelerator"))){f.next=2;break}return f.abrupt("return");case 2:return k=jQuery(p.parentNode).closest(".blck").first(),
q=k.find(".seraph_accel_spinner"),c=k.find('input[type="button"]'),q.show(),c.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,h=null,f.prev=9,f.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"QueueItemCancel",{pc:r,_wpnonce:l}),type:"GET",cache:!1,dataType:"json"});case 12:g=f.sent;h=z(g);f.next=19;break;case 16:f.prev=16,f.t0=f["catch"](9),h="HTTP "+f.t0.status;case 19:h&&alert(h),q.hide(),c.prop("disabled",!1),delete seraph_accel.Manager._int.notRefreshQueueDeleting;
case 23:case "end":return f.stop()}},n,this,[[9,16]])}));return Q.apply(this,arguments)}function P(){P=_asyncToGenerator(_regenerator.mark(function l(p,r){var n,k,q,c;return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:c=function(){c=_asyncToGenerator(_regenerator.mark(function f(){return _regenerator.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.next=2,seraph_accel.Manager._int.OnDataRefresh(p,r);case 2:k();case 3:case "end":return a.stop()}},f,this)}));return c.apply(this,
arguments)},q=function(){return c.apply(this,arguments)},k=function(){var g=1E3*parseInt(n.val(),10);100>g&&(g=100);clearTimeout(seraph_accel.Manager._int.refreshTimer);seraph_accel.Manager._int.refreshTimer=setTimeout(q,g)},n=jQuery(p).find("#operate .tmDataRefresh"),n.on("change",k),q();case 6:case "end":return h.stop()}},l,this)}));return P.apply(this,arguments)}function R(){R=_asyncToGenerator(_regenerator.mark(function l(p,r){var n,k,q,c,h,g,f,a,b,d,m,e,t,w,A,u,y,J,K,B,W;return _regenerator.wrap(function(L){for(;;)switch(L.prev=
L.next){case 0:return n=jQuery(p).find("#status").first(),k=jQuery(p).find("#stat").first(),q=k.find(".seraph_accel_spinner"),c=k.find('input[type="button"]:not(.cancel)'),h=k.find('input[type="button"].cancel'),g=jQuery(p).find("#operate").first(),f=g.find(".seraph_accel_spinner"),a=g.find(".descr"),b=g.find('input[type="button"]:not(.cancel)'),d=g.find('input[type="button"].cancel'),m=jQuery(p).find("#queue").first(),e=m.find(".content"),t=m.find(".maxItems"),w=m.find(".seraph_accel_spinner"),A=
m.find('input[type="button"]'),u=m.find(".descrNums"),L.prev=16,L.next=19,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"GetData",{nMaxQueueItems:t.val(),allSites:r?!0:void 0}),type:"GET",cache:!1,dataType:"json"});case 19:B=L.sent;L.next=24;break;case 22:L.prev=22,L.t0=L["catch"](16);case 24:if(B){L.next=26;break}return L.abrupt("return");case 26:if(!r){for(W in B.status.cont)n.find('[data-id-cont="'+W+'"]').html(B.status.cont[W]);seraph_accel.Manager._int.notRefreshPostUpd||
(y=n.find(".blck.postupd .seraph_accel_spinner"),J=n.find('.blck.postupd input[type="button"]:not(.cancel)'),K=n.find('.blck.postupd input[type="button"].cancel'),B.status.postUpd?(y.show(),J.prop("disabled",!0),K.prop("disabled",!1)):(y.hide(),J.prop("disabled",!1),K.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshScheUpd||(y=n.find(".blck.scheupd .seraph_accel_spinner"),J=n.find('.blck.scheupd input[type="button"]:not(.cancel)'),K=n.find('.blck.scheupd input[type="button"].cancel'),B.status.scheUpd?
(y.show(),J.prop("disabled",!0),K.prop("disabled",!1)):(y.hide(),J.prop("disabled",!1),K.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshCleanup||(y=n.find(".blck.cleanup .seraph_accel_spinner"),J=n.find('.blck.cleanup input[type="button"]:not(.cancel)'),K=n.find('.blck.cleanup input[type="button"].cancel'),B.status.cleanUp?(y.show(),J.prop("disabled",!0),K.prop("disabled",!1)):(y.hide(),J.prop("disabled",!1),K.prop("disabled",!0)))}r||seraph_accel.Manager._int.notRefreshExtDp||(y=n.find(".blck.extdb .seraph_accel_spinner"),
J=n.find('.blck.extdb input[type="button"]:not(.cancel)'),K=n.find('.blck.extdb input[type="button"].cancel'),B.extDb.isUpdating?(y.show(),J.prop("disabled",!0),K.prop("disabled",!1)):(y.hide(),J.prop("disabled",!1),K.prop("disabled",!0)));r||seraph_accel.Manager._int.notRefreshStat||(B.stat.isUpdating?(q.show(),c.prop("disabled",!0),h.prop("disabled",!1)):(q.hide(),c.prop("disabled",!1),h.prop("disabled",!0)),k.find('[data-id-cont="stat"]').html(B.stat.cont));r||seraph_accel.Manager._int.notRefreshOp||
(null===B.curOp&&(B.curOp=void 0),void 0!==B.curOp?(f.show(),a.show(),a.text(M(B.curOp)),b.prop("disabled",!0),d.prop("disabled",!1)):(f.hide(),a.hide(),b.prop("disabled",!1),d.prop("disabled",!0),a.text("")));e.html(B.queue.content);u.text(G(C("QueueNumsDescr_%1$u%2$u","admin.Manage","seraphinite-accelerator"),B.queue.nums.nInitial,B.queue.nums.nInProgress));seraph_accel.Manager._int.notRefreshQueueDeleting||(w.hide(),A.prop("disabled",!1),B.queue.isPaused?(m.find('input[type="button"].pause').hide(),
m.find('input[type="button"].resume').show()):(m.find('input[type="button"].pause').show(),m.find('input[type="button"].resume').hide()));case 33:case "end":return L.stop()}},l,this,[[16,22]])}));return R.apply(this,arguments)}function S(){S=_asyncToGenerator(_regenerator.mark(function r(p){var l,n,k,q,c,h,g,f;return _regenerator.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return l=jQuery(p.parentNode).closest(".blck").first(),n=l.find(".url"),k=l.find(".messages"),q=l.find(".seraph_accel_spinner"),
c=l.find('input[type="button"]'),h=0,l.find(".liteChk").prop("checked")&&(h|=1),l.find(".medChk").prop("checked")&&(h|=2),l.find(".tidyChk").prop("checked")&&(h|=524288),k.empty(),q.show(),c.prop("disabled",!0),a.prev=12,a.next=15,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"HtmlCheck",{url:n.val(),norm:h}),type:"POST",data:"",dataType:"json",cache:!1});case 15:g=a.sent;a.next=21;break;case 18:a.prev=18,a.t0=a["catch"](12),g={err:a.t0.statusText};case 21:q.hide();
c.prop("disabled",!1);if(!g.err){a.next=26;break}k.append(seraph_accel.Ui.LogItem("error",g.err));return a.abrupt("return");case 26:for(f in g.list)f=g.list[f],k.append(seraph_accel.Ui.LogItem(f.severity,f.text));case 27:case "end":return a.stop()}},r,this,[[12,18]])}));return S.apply(this,arguments)}var V=seraph_accel.Wp.Loc.GetApi(),C=V._x,G=V.sprintf;seraph_accel.Settings={_int:{OnUpdateCssAuto:function(v){seraph_accel.Ui.ComboShowDependedItems(v,jQuery(v.parentNode).closest(".blck").first().get(0))},
OnLogClear:function(v){return x.apply(this,arguments)}}};seraph_accel.Manager={_int:{OnStatOp:function(v,p){return N.apply(this,arguments)},OnCacheOp:function(v,p,r){return E.apply(this,arguments)},OnCacheOpCancel:function(v,p,r){return O.apply(this,arguments)},OnPostUpdCancel:function(v){return H.apply(this,arguments)},OnScheUpdCancel:function(v){return F.apply(this,arguments)},OnExtDbUpdBegin:function(v){return D.apply(this,arguments)},OnExtDbUpdCancel:function(v){return I.apply(this,arguments)},
OnQueueDel:function(v,p,r){return T.apply(this,arguments)},OnQueuePause:function(v,p,r){return U.apply(this,arguments)},OnQueueItemCancel:function(v,p,r){return Q.apply(this,arguments)},OnDataRefreshInit:function(v,p){return P.apply(this,arguments)},OnDataRefresh:function(v,p){return R.apply(this,arguments)},OnHtmlCheck:function(v){return S.apply(this,arguments)}}};(function(){function v(n){return p.apply(this,arguments)}function p(){p=_asyncToGenerator(_regenerator.mark(function q(k){var c,h;return _regenerator.wrap(function(g){for(;;)switch(g.prev=
g.next){case 0:return c={},g.prev=1,seraph_accel.SelfDiag._int.curAjax=jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"SelfDiag_"+k,{}),cache:!1,dataType:"json"}),g.next=5,seraph_accel.SelfDiag._int.curAjax;case 5:c=g.sent;delete seraph_accel.SelfDiag._int.curAjax;g.next=14;break;case 9:g.prev=9,g.t0=g["catch"](1),delete seraph_accel.SelfDiag._int.curAjax,0===g.t0.status?c.hr=seraph_accel.Gen.hr.S_ABORTED:(c.hr=seraph_accel.Gen.hr.E_FAIL,c.descr="HTTP "+g.t0.status),
500==g.t0.status&&(h=document.implementation.createHTMLDocument(""),h.documentElement.innerHTML=g.t0.responseText,h=h.body.textContent,h=seraph_accel.Gen.StrReplaceAll(h,"\r",""),h=seraph_accel.Gen.StrReplaceAll(h,["\t","\v"]," "),h=seraph_accel.Gen.StrReplaceAll(h,"\n",". "),(h=seraph_accel.Gen.StrReplaceAllWhileChanging(h,["  ",". . "],[" ",". "]).trim())&&"."!=h&&(c.descr+="<br>"+h));case 14:return g.abrupt("return",c);case 15:case "end":return g.stop()}},q,this,[[1,9]])}));return p.apply(this,
arguments)}function r(){r=_asyncToGenerator(_regenerator.mark(function q(k){var c,h,g,f,a,b,d,m,e,t,w,A=arguments;return _regenerator.wrap(function(u){for(;;)switch(u.prev=u.next){case 0:c=1<A.length&&void 0!==A[1]?A[1]:!1;h=jQuery(k.parentNode).closest(".blck").first();g=h.find(".seraph_accel_spinner");f=h.find('input[type="button"]:not(.cancel)');a=h.find('input[type="button"].cancel');b=h.find(".log");d=[{id:"3rdPartySettCompat",name:l("TestName_3rdPartySettCompat","admin.SelfDiag","seraphinite-accelerator")},
{id:"AsyncRequest",name:l("TestName_AsyncRequest","admin.SelfDiag","seraphinite-accelerator")},{id:"SetMaxExecTime",name:l("TestName_SetMaxExecTime","admin.SelfDiag","seraphinite-accelerator")},{id:"PageOptimize",name:l("TestName_PageOptimize","admin.SelfDiag","seraphinite-accelerator")},{id:"VendorSrv",name:l("TestName_VendorSrv","admin.SelfDiag","seraphinite-accelerator")},{id:"ExtCache",name:l("TestName_ExtCache","admin.SelfDiag","seraphinite-accelerator")}];b.empty();for(m=0;m<d.length;m++)e=
d[m],b.append(seraph_accel.Ui.LogItem("none",seraph_accel.Ui.Tag("strong",e.name?e.name:e.id),!1));if(!c){u.next=11;break}return u.abrupt("return");case 11:g.show(),f.prop("disabled",!0),a.prop("disabled",!1),seraph_accel.SelfDiag._int.inProgress=!0,m=0;case 16:if(!(m<d.length)){u.next=31;break}e=d[m];jQuery(b.children().get(m)).replaceWith(seraph_accel.Ui.LogItem("info",seraph_accel.Ui.Tag("strong",e.name?e.name:e.id)+l("TestRunning","admin.SelfDiag","seraphinite-accelerator"),!1));u.next=21;return v(e.id);
case 21:t=u.sent;w=l("TestSucc","admin.SelfDiag","seraphinite-accelerator");t.hr!=seraph_accel.Gen.hr.S_OK&&(w=seraph_accel.Gen.hr.Succ(t.hr)?t.hr==seraph_accel.Gen.hr.S_ABORTED?l("TestAbort","admin.SelfDiag","seraphinite-accelerator"):t.hr==seraph_accel.Gen.hr.S_FALSE?l("TestNotice","admin.SelfDiag","seraphinite-accelerator"):l("TestWarn","admin.SelfDiag","seraphinite-accelerator"):l("TestError","admin.SelfDiag","seraphinite-accelerator"));t.descr&&(w+="<br>"+t.descr);jQuery(b.children().get(m)).replaceWith(seraph_accel.Ui.LogItem(t.hr==
seraph_accel.Gen.hr.S_OK?"success":seraph_accel.Gen.hr.Succ(t.hr)?t.hr==seraph_accel.Gen.hr.S_FALSE?"normal":"warning":"error",seraph_accel.Ui.Tag("strong",e.name?e.name:e.id)+w,!1));if(seraph_accel.SelfDiag._int.inProgress){u.next=28;break}return u.abrupt("break",31);case 28:m++;u.next=16;break;case 31:g.hide(),f.prop("disabled",!1),a.prop("disabled",!0);case 34:case "end":return u.stop()}},q,this)}));return r.apply(this,arguments)}var l=seraph_accel.Wp.Loc.GetApi()._x;seraph_accel.SelfDiag={_int:{OnStart:function(n){return r.apply(this,
arguments)},OnCancel:function(n){n=jQuery(n.parentNode).closest(".blck").first();n.find(".seraph_accel_spinner");n.find('input[type="button"]:not(.cancel)');n.find('input[type="button"].cancel').prop("disabled",!0);seraph_accel.SelfDiag._int.inProgress=!1;seraph_accel.SelfDiag._int.curAjax&&seraph_accel.SelfDiag._int.curAjax.abort()},inProgress:!1}}})()})();
